#pragma once

/*#ifndef ZSTANDALONE
	#define ENABLE_ZASSERTS
	#define ENABLE_ZDEBUG
	#define ENABLE_ZERROR
#else
	#undef ENABLE_ZASSERTS
	#undef ENABLE_ZDEBUG
	#undef ENABLE_ZERROR
#endif*/

/*#define PRODUCTION_NAME "yportne by fnuque"
#define PROJECT_HEADER_FILE "projects/yportne/main.intruderproject.h"
#define SYNC_HEADER_FILE "projects/yportne/sync.rocket.h"

#ifdef _DEBUG
	// debug build
	#undef ENABLE_STARTUP_DIALOG
	#define ENABLE_MUSIC_LOAD_EXTERNAL
	#define ENABLE_GUI
	#define ENABLE_ASSERTS		
	#define ENABLE_ZDEBUG
	#define ENABLE_CONSOLE
	#define ENABLE_SCRUBBER
	#undef ENABLE_HEADER_LOAD
	#define WINDOW_TITLE "Intruder"
	#undef ENABLE_STANDALONE
	#undef SYNC_PLAYER
	#undef ENABLE_REALTIME_MUSIC
#else
	#ifndef INTRUDER_SMALL
		// release build
		#undef ENABLE_STARTUP_DIALOG
		#define ENABLE_MUSIC_LOAD_EXTERNAL
		#define ENABLE_GUI
		#define ENABLE_ASSERTS		
		#define ENABLE_ZDEBUG
		#define ENABLE_CONSOLE
		#define ENABLE_SCRUBBER
		#undef ENABLE_HEADER_LOAD
		#define WINDOW_TITLE "Intruder"
		#undef ENABLE_STANDALONE
		#undef SYNC_PLAYER
		#undef ENABLE_REALTIME_MUSIC
	#else
		// release small
		#define ENABLE_STARTUP_DIALOG
		#undef ENABLE_MUSIC_LOAD_EXTERNAL
		#undef ENABLE_GUI
		#undef ENABLE_ASSERTS
		#undef ENABLE_ZDEBUG
		#undef ENABLE_CONSOLE
		#undef ENABLE_SCRUBBER
		#define ENABLE_HEADER_LOAD
		#define WINDOW_TITLE PRODUCTION_NAME
		#define ENABLE_STANDALONE
		#define SYNC_PLAYER
		#define ENABLE_REALTIME_MUSIC
	#endif
#endif

#undef ENABLE_EFFECT_DRAWCUBE
#define ENABLE_EFFECT_DRAWMESH
#undef ENABLE_EFFECT_FULLSCREENQUAD
#define ENABLE_EFFECT_PLANE
#undef ENABLE_EFFECT_ROCK
#undef ENABLE_EFFECT_SPAWN
#undef ENABLE_EFFECT_SUBDIVSPHERE
#undef ENABLE_EFFECT_SUPERELLIPSOID
#undef ENABLE_EFFECT_SUPERSHAPE3D
#define ENABLE_EFFECT_TEXT
#define ENABLE_EFFECT_PPFEEDBACK
#define ENABLE_EFFECT_PARTICLES
#define ENABLE_ROCKET
#undef ENABLE_EFFECT_WOBBLESYNC
#undef ENABLE_EFFECT_MESHTUNNEL
#undef ENABLE_EFFECT_MESHTUNNELLOOKAT
#undef ENABLE_EVENT_SYNC*/
